### ISSUE TITLE
可以请教项目作者几个问题吗？

### ISSUE THREAD

**Issue by JasonStepan** [mzh3511/OdExamplesMgd#1]
您好：
  就是我目前在做CAD解析相关的项目，用的是LibreCAD，但是由于LibreCAD不支持OLE2，之后去网上搜了很多资料，看到作者的这个example是支持OLE的。请问您，这个项目还能增加导出图片的功能吗？

**Comment by JasonStepan** [comment]
> 您好：
> 就是我目前在做CAD解析相关的项目，用的是LibreCAD，但是由于LibreCAD不支持OLE2，之后去网上搜了很多资料，看到作者的这个example是支持OLE的。请问您，这个项目还能增加导出图片的功能吗？

**Comment by JasonStepan** [comment]
> 您好：
> 就是我目前在做CAD解析相关的项目，用的是LibreCAD，但是由于LibreCAD不支持OLE2，之后去网上搜了很多资料，看到作者的这个example是支持OLE的。请问您，这个项目还能增加导出图片的功能吗？

另外我有了解到，这个example其实是C#写的，然后核心库其实是open design的，不知道是否有C++的example？

**Comment by mzh3511** [comment]
抱歉，这个代码是我在网上找来做测试确定使用哪个三方组件用的，实际也没怎么了解，后来公司使用了VectorDraw (www.vdraw.com/​)
